spring:
  profiles:
      active:
        - dog
        - EN
        - prod
com:
  username: YmlUsername
  password: YmlPassword
  jdbcurl: YmlJdbcurl

---
spring:
  config:
    activate:
      on-profile: prod

com:
  username: YmlProdUsername
  password: YmlProdPassword
  jdbcurl: YmlProdJdbcurl
